#define CLI_ENABLE 8

// DS18B20 Temperature 
#define ONE_WIRE_BUS 6

// HUMIDITY SENSOR
#define DHTPIN 5
#define DHTTYPE DHT11

//INTERRUPTS
#define ALARM_PIN 3

//ANALOG READ PINS
#define BATT_V_PIN A0
#define SOLAR_V_PIN A1